import { ENV_CONFIG } from '../utils/env-config'

export const API_CONFIG = {
	SERVICE_BASE_URL: {
		RECOMMENDATION: ENV_CONFIG.RECOMMENDATION_SERVICE_URL,
		USER: ENV_CONFIG.USER_SERVICE_URL,
		TRAVEL: ENV_CONFIG.TRAVEL_SERVICE_URL,
	},
	TIMEOUT: ENV_CONFIG.API_TIMEOUT,
	ENVIRONMENT: ENV_CONFIG.NODE_ENV,
}
